### ISSUE TITLE
Need Xmidt architecture details

### ISSUE THREAD

**Issue by ganeshprasads** [Comcast/xmidt#1]
We are setting up a minimal webPA cluster for RDK-M, as per our understanding we are setting up the webPA cluster having 4 nodes with following node allocation:
1x Talaria, 1x Cadeceus, 1x Petasos, 1x Scytale
- As Xmidt and tr1d1um are introduced recently, we wanted to know how these new components will fit in. i.e. whether these services will sit with any of the above nodes or need dedicated servers to run.
- Also any architecture detail or diagram pointing out communication flow will be good for us to understand the whole ecosystem & implementation.

Regards
Ganesh

**Comment by schmidtw** [comment]
I've added an architecture diagram & the start of the theory of operation for Xmidt here:
https://github.com/Comcast/xmidt/wiki/Architecture

Tr1d1um is the Webpa server it depends on Xmidt.

It is possible to install all 4 on the same VM, though I don't have a configuration for that.  If you can create on, that would be fantastic.

**Comment by fchan2** [comment]
I recently installed a WebPA cluster with 3 nodes -- tr1d1um, scytale, and talaria -- on the same VM.

I installed each package from the https://github.com/comcast repo. In addition, I also needed to install zookeeper as a dependency for those nodes. I am running CentOS 6 on the VM.

The service flow is as follows:
tr1d1um --> scytale --> talaria <--> RDK
