### ISSUE TITLE
What are the compatible CentOS versions

### ISSUE THREAD

**Issue by ganeshprasads** [Comcast/xmidt#2]
We want to deploy the Xmidt server components for RDK Tech summit on a AWS VM and amazon currently gives option to create instances using CentOS 6.4 & 7.0 versions.
What CentOS versions are currently compatible for deploying Xmidt server components?.

Regards
Ganesh

**Comment by schmidtw** [comment]
Using the startup scripts present, Centos 6.x is supported & tested today.
